import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import copy from "esbuild-plugin-copy";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Set up directories
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(
  __dirname,
  "demo_vault/.obsidian/plugins/obsidian-flashcards-plugin",
);
const srcDir = path.join(__dirname, "src");

// Ensure output directory exists
if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

// Build options
const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: [path.join(srcDir, "main.ts")],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  plugins: [
    sveltePlugin({
      preprocess: sveltePreprocess({
        sourceMap: !prod,
      }),
      compilerOptions: {
        dev: !prod,
        css: "injected",
      },
    }),
    copy({
      assets: [
        {
          from: path.join(__dirname, "manifest.json"),
          to: path.join(outDir, "manifest.json"),
        },
      ],
    }),
  ],
};

// Build
esbuild.build(buildOptions).catch((err) => {
  console.error(err);
  process.exit(1);
});
